INSERT OR IGNORE INTO courses (id, school_id, code, name, status, created_by) VALUES
-- School of Biological Sciences (SBS)
('course_sbs_b101', 'sbs', 'B101', 'Biology I: Science of Life', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b141', 'sbs', 'B141', 'Biology Laboratory-1', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b102', 'sbs', 'B102', 'Biology II: Cellular and Genetic basis of life', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b142', 'sbs', 'B142', 'Biology Laboratory-2', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b201', 'sbs', 'B201', 'Microbiology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b202', 'sbs', 'B202', 'Biochemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b241', 'sbs', 'B241', 'Laboratory-3 (Microbiology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b242', 'sbs', 'B242', 'Laboratory-4 (Biochemistry)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b204', 'sbs', 'B204', 'Cell Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b206', 'sbs', 'B206', 'Molecular Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b243', 'sbs', 'B243', 'Laboratory-5 (Cell Biology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b245', 'sbs', 'B245', 'Laboratory-6 (Molecular Biology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b301', 'sbs', 'B301', 'Physiology-I (Animal)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b302', 'sbs', 'B302', 'Physiology-II (Plant)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b341', 'sbs', 'B341', 'Laboratory-7 (Animal Physiology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b342', 'sbs', 'B342', 'Laboratory-8 (Plant Physiology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b303', 'sbs', 'B303', 'Ecology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b305', 'sbs', 'B305', 'Immunology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b307', 'sbs', 'B307', 'Genetics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b344', 'sbs', 'B344', 'Laboratory-10 (Immunology)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b345', 'sbs', 'B345', 'Laboratory-9 (Genetics)', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b306', 'sbs', 'B306', 'Evolutionary biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b402', 'sbs', 'B402', 'Developmental Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b405', 'sbs', 'B405', 'Bio-techniques', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b498', 'sbs', 'B498', 'Biology Project', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b406', 'sbs', 'B406', 'Introductory Biophysics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b403', 'sbs', 'B403', 'Bioinformatics and Computational Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b407', 'sbs', 'B407', 'Quantitative and user_3Gl6Q2aBCfE9iUvKxkju4MHBiIGs Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b499', 'sbs', 'B499', 'Biology Project', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b598', 'sbs', 'B598', 'Biology Project /Dissertation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b599', 'sbs', 'B599', 'Biology Project /Dissertation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b451', 'sbs', 'B451', 'Advanced Cell Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b452', 'sbs', 'B452', 'Genetic engineering', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b453', 'sbs', 'B453', 'Advance Biochemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b454', 'sbs', 'B454', 'Advance Microbiology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b455', 'sbs', 'B455', 'Enzymology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b456', 'sbs', 'B456', 'Advance Neurobiology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b457', 'sbs', 'B457', 'Chemical Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b460', 'sbs', 'B460', 'Virology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b461', 'sbs', 'B461', 'Principles of Drug Design', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b462', 'sbs', 'B462', 'Endocrinology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b463', 'sbs', 'B463', 'Plant Developmental Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b464', 'sbs', 'B464', 'Neurobiology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b465', 'sbs', 'B465', 'Structural Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b466', 'sbs', 'B466', 'Model Organisms in Biomedical Research', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b551', 'sbs', 'B551', 'Advanced Molecular Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b552', 'sbs', 'B552', 'Advanced Immunology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b553', 'sbs', 'B553', 'Infectious Disease Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b554', 'sbs', 'B554', 'Cancer Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b555', 'sbs', 'B555', 'Advanced Genetics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b556', 'sbs', 'B556', 'Immune regulation and Infection immunity', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b557', 'sbs', 'B557', 'Macromolecular crystallography', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b559', 'sbs', 'B559', 'Ion Channels', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b561', 'sbs', 'B561', 'Concepts in Mechanobiology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b562', 'sbs', 'B562', 'Molecular errors in disease pathogenesis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]
('course_sbs_b563', 'sbs', 'B563', 'Translational Control in Biology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 1]

-- School of Chemical Sciences (SCS)
('course_scs_c101', 'scs', 'C101', 'Chemistry-I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c141', 'scs', 'C141', 'Chemistry Laboratory-I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c102', 'scs', 'C102', 'Chemistry-II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c142', 'scs', 'C142', 'Chemistry Laboratory-II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c201', 'scs', 'C201', 'Basic inorganic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c203', 'scs', 'C203', 'Reaction Mechanisms in Organic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c207', 'scs', 'C207', 'Mathematical Methods for Chemists', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c245', 'scs', 'C245', 'Inorganic Chemistry Lab.', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c204', 'scs', 'C204', 'Reagents in Organic Syntheses', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c205', 'scs', 'C205', 'Main group and Organometallic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c206', 'scs', 'C206', 'Quantum Chemistry I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c243', 'scs', 'C243', 'Physical Chemistry Lab I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c244', 'scs', 'C244', 'Biomolecular Chemistry Lab', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c301', 'scs', 'C301', 'Physical Organic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c302', 'scs', 'C302', 'Molecular Spectroscopy and group Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c307', 'scs', 'C307', 'Thermodynamics and Electrochemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c341', 'scs', 'C341', 'Organic Chemistry Lab I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c342', 'scs', 'C342', 'Inorganic Chemistry Lab I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c304', 'scs', 'C304', 'Coordination Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c305', 'scs', 'C305', 'Chemical Binding', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c306', 'scs', 'C306', 'Physical Methods in Chemistry I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c343', 'scs', 'C343', 'Physical Chemistry Lab II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c344', 'scs', 'C344', 'Organic Chemistry Lab II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c401', 'scs', 'C401', 'Physical Methods in Chemistry II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c403', 'scs', 'C403', 'Chemistry of Heterocycles and Natural Products', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c498', 'scs', 'C498', 'Chemistry project', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c402', 'scs', 'C402', 'Chemical Rate Processes', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c499', 'scs', 'C499', 'Chemistry Project', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c598', 'scs', 'C598', 'Chemistry Project', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c599', 'scs', 'C599', 'Chemistry Dissertation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c351', 'scs', 'C351', 'Photochemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c352', 'scs', 'C352', 'Pharmaceutical Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c353', 'scs', 'C353', 'Classics in Molecules', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c551', 'scs', 'C551', 'Molecular Modeling', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c552', 'scs', 'C552', 'Solid State Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c554', 'scs', 'C554', 'Crystallography', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c555', 'scs', 'C555', 'Principles of Drug action', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c556', 'scs', 'C556', 'Advanced Bio-inorganic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c557', 'scs', 'C557', 'Nuclear Magnetic Resonance', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c558', 'scs', 'C558', 'Advanced Functional Materials', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c559', 'scs', 'C559', 'Supramolecular Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c560', 'scs', 'C560', 'Chemistry of Nanomaterials', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c561', 'scs', 'C561', 'Advanced Bio-organic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c562', 'scs', 'C562', 'Polymer Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c563', 'scs', 'C563', 'Molecular Reaction Dynamics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c564', 'scs', 'C564', 'Theory of Molecular Spectroscopy', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c565', 'scs', 'C565', 'Advanced Organic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c566', 'scs', 'C566', 'Catalysis: Reaction Mechanisms and Applications', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c567', 'scs', 'C567', 'Advanced Main group Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c568', 'scs', 'C568', 'Advanced Fluorescence Spectroscopy', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c569', 'scs', 'C569', 'Biomacromolecules', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c570', 'scs', 'C570', 'Advanced Heterocyclic Chemistry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]
('course_scs_c571', 'scs', 'C571', 'Statistical Mechanics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 2]

-- School of Computer Sciences (SCoS)
('course_scos_cs456', 'scos', 'CS456', 'Computational Geometry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs457', 'scos', 'CS457', 'Parameterized Algorithms', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs458', 'scos', 'CS458', 'Approximation Algorithms', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs459', 'scos', 'CS459', 'Algorithmic Game Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs460', 'scos', 'CS460', 'Machine Learning', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs461', 'scos', 'CS461', 'Advanced Machine Learning', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs472', 'scos', 'CS472', 'Introduction to Computational Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]
('course_scos_cs473', 'scos', 'CS473', 'Advanced Computational Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 3]

-- School of Mathematical Sciences (SMS)
('course_sms_m101', 'sms', 'M101', 'Mathematics-I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m102', 'sms', 'M102', 'Mathematics-II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m201', 'sms', 'M201', 'Real Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m202', 'sms', 'M202', 'Group Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m203', 'sms', 'M203', 'Discrete Mathematics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m204', 'sms', 'M204', 'Metric Spaces', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m205', 'sms', 'M205', 'Linear Algebra', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m206', 'sms', 'M206', 'Probability Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m301', 'sms', 'M301', 'Lebesgue Integration', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m302', 'sms', 'M302', 'Rings and Modules', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m303', 'sms', 'M303', 'Differential Equations', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m305', 'sms', 'M305', 'Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m306', 'sms', 'M306', 'Calculus of Several Variables', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m307', 'sms', 'M307', 'Field Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m308', 'sms', 'M308', 'Complex Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m309', 'sms', 'M309', 'Graph Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m401', 'sms', 'M401', 'Functional Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m402', 'sms', 'M402', 'Representations of Finite Groups', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m405', 'sms', 'M405', 'Topology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m406', 'sms', 'M406', 'Geometry of Curves and Surfaces', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m598', 'sms', 'M598', 'Dissertation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m599', 'sms', 'M599', 'Dissertation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m451', 'sms', 'M451', 'Advanced Complex Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m452', 'sms', 'M452', 'Advanced Functional Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m453', 'sms', 'M453', 'Advanced Linear Algebra', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m454', 'sms', 'M454', 'Partial Differential Equations', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m455', 'sms', 'M455', 'Introduction to Stochastic Processes', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m456', 'sms', 'M456', 'Algebraic Geometry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m457', 'sms', 'M457', 'Algebraic Graph Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m458', 'sms', 'M458', 'Algebraic Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m459', 'sms', 'M459', 'Statistics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m460', 'sms', 'M460', 'Algorithm', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m461', 'sms', 'M461', 'Numerical Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m462', 'sms', 'M462', 'Cryptology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m463', 'sms', 'M463', 'Finite Fields', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m464', 'sms', 'M464', 'Information and Coding Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m465', 'sms', 'M465', 'Mathematical Logic', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m466', 'sms', 'M466', 'Measure Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m467', 'sms', 'M467', 'Nonlinear Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m468', 'sms', 'M468', 'Operator Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m469', 'sms', 'M469', 'Theory of Computation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m470', 'sms', 'M470', 'Abstract Harmonic Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m471', 'sms', 'M471', 'Advanced Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m472', 'sms', 'M472', 'Advanced Probability', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m473', 'sms', 'M473', 'Algebraic Combinatorics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m474', 'sms', 'M474', 'Foundations of Cryptography', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m475', 'sms', 'M475', 'Incidence Geometry', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m476', 'sms', 'M476', 'Lie Algebras', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m477', 'sms', 'M477', 'Optimization Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m478', 'sms', 'M478', 'Advanced Partial Differential Equations', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m479', 'sms', 'M479', 'Random Graphs', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m480', 'sms', 'M480', 'Randomized Algorithms and Probabilistic Methods', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m481', 'sms', 'M481', 'Statistical Inference-I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m482', 'sms', 'M482', 'Multivariate Statistical Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m483', 'sms', 'M483', 'Introduction to Manifolds', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m484', 'sms', 'M484', 'Commutative Algebra', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m485', 'sms', 'M485', 'Algebraic Topology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m551', 'sms', 'M551', 'Algebraic Computation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m552', 'sms', 'M552', 'Analytic Number Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m553', 'sms', 'M553', 'Classical Groups', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m554', 'sms', 'M554', 'Ergodic Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m555', 'sms', 'M555', 'Harmonic Analysis', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m556', 'sms', 'M556', 'Lie Groups and Lie Algebras-I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m557', 'sms', 'M557', 'Operator Algebras', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m558', 'sms', 'M558', 'Representations of Linear Lie Groups', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m559', 'sms', 'M559', 'Harmonic Analysis on Compact Groups', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m560', 'sms', 'M560', 'Modular Forms of One Variable', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m561', 'sms', 'M561', 'Elliptic Curves', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m562', 'sms', 'M562', 'Brownian Motion and Stochastic Calculus', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m563', 'sms', 'M563', 'Differentiable Manifolds and Lie Groups', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m564', 'sms', 'M564', 'Lie Groups and Lie Algebras-II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m565', 'sms', 'M565', 'Mathematical Foundations for Finance', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m566', 'sms', 'M566', 'Designs and Codes', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m567', 'sms', 'M567', 'Statistical Inference-II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m568', 'sms', 'M568', 'Ordered Linear Spaces', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m569', 'sms', 'M569', 'Topics in HP Spaces', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]
('course_sms_m570', 'sms', 'M570', 'Introduction to Dilation Theory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 4]

-- School of Physical Sciences (SPS)
('course_sps_p101', 'sps', 'P101', 'Introductory Physics I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p141', 'sps', 'P141', 'Physics Laboratory I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p102', 'sps', 'P102', 'Introductory Physics II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p142', 'sps', 'P142', 'Physics Laboratory II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p201', 'sps', 'P201', 'Classical Mechanics I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p202', 'sps', 'P202', 'Mathematical Methods I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p207', 'sps', 'P207', 'Linear Optics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p241', 'sps', 'P241', 'General Physics Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p245', 'sps', 'P245', 'Basic Electronics theory and Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p204', 'sps', 'P204', 'Electromagnetism I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p205', 'sps', 'P205', 'Mathematical Methods II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p206', 'sps', 'P206', 'Quantum Mechanics I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p246', 'sps', 'P246', 'Advanced Electronics theory and Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p302', 'sps', 'P302', 'Statistical Mechanics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p303', 'sps', 'P303', 'Quantum Mechanics II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p304', 'sps', 'P304', 'Special Theory of Relativity', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p346', 'sps', 'P346', 'Computational Physics Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p345', 'sps', 'P345', 'Optics Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p343', 'sps', 'P343', 'Modern Physics Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p301', 'sps', 'P301', 'Electromagnetism II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p306', 'sps', 'P306', 'Introduction to Condensed Matter Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p307', 'sps', 'P307', 'Nuclei and Particles', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p341', 'sps', 'P341', 'Nuclear Physics & Instrumentation Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p347', 'sps', 'P347', 'Solid State Physics Laboratory', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p401', 'sps', 'P401', 'Classical Mechanics II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p305', 'sps', 'P305', 'Atoms, Molecules and Radiation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p445', 'sps', 'P445', 'Integrated Physics Laboratory I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p446', 'sps', 'P446', 'Integrated Physics Laboratory II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p598', 'sps', 'P598', 'Physics Dissertation project I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p599', 'sps', 'P599', 'Physics Dissertation project I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p451', 'sps', 'P451', 'Advanced Solid State Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p452', 'sps', 'P452', 'Computational Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p453', 'sps', 'P453', 'Quantum Field theory I', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p454', 'sps', 'P454', 'Particle Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p455', 'sps', 'P455', 'Introduction to Phase Transition and Critical Phenomena', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p456', 'sps', 'P456', 'Nonlinear Optics and Lasers', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p457', 'sps', 'P457', 'General Theory of Relativity and Cosmology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p458', 'sps', 'P458', 'Soft Condensed Matter', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p459', 'sps', 'P459', 'Applied Nuclear Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p460', 'sps', 'P460', 'Many Particle Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p461', 'sps', 'P461', 'Physics of Mesoscopic user_3Gl6Q2aBCfE9iUvKxkju4MHBiIGs', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p462', 'sps', 'P462', 'Introduction to Quantum Optics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p463', 'sps', 'P463', 'Astronomy and Astrophysics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p464', 'sps', 'P464', 'Plasma Physics and Magneto-hydrodynamics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p466', 'sps', 'P466', 'Quantum and Nano-electronics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p467', 'sps', 'P467', 'Nonlinear Physics Chaos and Turbulence', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p468', 'sps', 'P468', 'Magnetism and Superconductivity', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p469', 'sps', 'P469', 'Density Functional Theory of Atoms, Molecules and Solids', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p470', 'sps', 'P470', 'Quantum Field Theory II', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p471', 'sps', 'P471', 'Quantum Information and Quantum Computation', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p472', 'sps', 'P472', 'Experimental High Energy Physics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p473', 'sps', 'P473', 'Experimental Techniques', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p474', 'sps', 'P474', 'Introduction to Cosmology', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p477', 'sps', 'P477', 'Relativistic Nucleus-Nucleus collision and Quark-Gluon Plasma', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p476', 'sps', 'P476', 'Nonequilibrium -Statistical Mechanics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'), --[cite: 5]
('course_sps_p475', 'sps', 'P475', 'Special topics in quantum mechanics', 'approved', 'user_3Gl6Q2aBCfE9iUvKxkju4MHBiIG'); --[cite: 5]
